"""add processing_status to notifications

Revision ID: 25d3d2cf9bd4
Revises: 0532ad6ddf4e
Create Date: 2026-09-20 19:00:57.776910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d3d2cf9bd4'
down_revision: Union[str, None] = '0532ad6ddf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_attendances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PRESENT', 'ABSENT', name='attendancestatus'),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='processingstatus'), server_default='PENDING', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index('idx_notifications_processing_status', ['processing_status'], unique=False)
        batch_op.create_index('idx_notifications_student_status', ['student_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_processing_status'))
        batch_op.drop_index('idx_notifications_student_status')
        batch_op.drop_index('idx_notifications_processing_status')
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('processing_status')

    with op.batch_alter_table('daily_attendances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', name='attendancestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
