"""make published_at nullable

Revision ID: eedbb6739860
Revises: 001
Create Date: 2026-09-16 21:29:37.012186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedbb6739860'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('published_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_announcements_source_reference'), ['source_reference'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_source_id'), ['source_id'], unique=False)

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_materials_uploaded_by_student_id'))

    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_started_at'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_started_at'), ['started_at'], unique=False)

    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_materials_uploaded_by_student_id'), ['uploaded_by_student_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_source_id'))

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_source_reference'))
        batch_op.alter_column('published_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
